### ISSUE TITLE
Lya simulation crashing with: New timestep < old

### ISSUE THREAD

**Issue by Plaetean** [rainwoodman/MP-Gadget#149]
Hello everyone, my name is Chris and I've just started a PhD with Andreu at UCL. I'm looking at simulating Lyman alpha, and I get the following error:

`[ 000006.78 ] Task 20: Time error: New timestep (0.0243902) < old (0.0243902)!`

This error only crops up at certain starting redshifts (z=10, z=40 and z=60) and the run crashes immediately. I tried a range of sims with different box sizes and starting [redshfits shown here and the red boxes are the sims which crash.](https://imgur.com/a/yF7tR). I have attached the Options.mk and paramfiles I am using (had to convert them to .txt to upload them).

[Options.txt](https://github.com/rainwoodman/MP-Gadget/files/1417874/Options.txt)
[paramfile_gadget.txt](https://github.com/rainwoodman/MP-Gadget/files/1417875/paramfile_gadget.txt)
[paramfile_genic.txt](https://github.com/rainwoodman/MP-Gadget/files/1417876/paramfile_genic.txt)

Is this an issue or am I doing something wrong? Also happy to investigate with other parameters - if you have access to hypatia I've put the sims that failed in:

`/home/chrisp/Projects/testSims/borkedJobs`

Thanks!

**Comment by andreufont** [comment]
I was able to reproduce the error on a different computer, using a different compiler.

It crashes even when using a single node, a single processor, and it crashes at the first time step.

**Comment by sbird** [comment]
This is definitely a real issue. I can't reproduce it (probably because I have a newer glibc and thus the floating point functions have slightly different accuracy). It is because on the first timestep set_global_time will be called twice with the same Time parameter, and there may be floating point roundoff making the timestep seem negative. Please try #152 and see if it fixes the problem.
