### ISSUE TITLE
No structure evolution when running with massive neutrinos + baryon physics

### ISSUE THREAD

**Issue by Chris-Pedersen** [rainwoodman/MP-Gadget#178]
When running with massive neutrinos and baryon physics, the runs take about 1/10th the normal time, so I looked at some power spectra and noticed that there was basically no evolution between z=99 and z=2. It it looks like these sims are somehow not growing any structure. Output file here:
[test_out.txt](https://github.com/rainwoodman/MP-Gadget/files/1557713/test_out.txt)

**Comment by sbird** [comment]
Here:
InputPowerRedshift              0                    # Redshift at which the input power is. Power spectrum will be rescaled to the initial redshift. Negative disables rescaling.
This tells GenIC that the input power is at redshift 0, but your CAMB file is at z=99. So GenIC rescales it down by a factor of 100, ensuing that you have essentially a homogeneous box, which is why structure does not grow.

Set InputPowerRedshift = -1

**Comment by Chris-Pedersen** [comment]
Ahh I see - thank you.
