### ISSUE TITLE
Slow treewalk with lots of wait time

### ISSUE THREAD

**Issue by sbird** [rainwoodman/MP-Gadget#200]
See this comment: 

https://github.com/rainwoodman/MP-Gadget/pull/194#issuecomment-361781673
and
https://github.com/rainwoodman/MP-Gadget/pull/194#issuecomment-361788945

**Comment by rainwoodman** [comment]
It was like this in BlueTides-I as well.

**Comment by rainwoodman** [comment]
It wasn't like this in MassiveBlack-II. So it is a very old change that produced this.

**Comment by rainwoodman** [comment]
I see why!

It wasn't our tree is slower. It was because our PM is faster. 

Nishi told me the rule of thumb is that PM time shall be equal to the treegrav time. This is the cause of my concerns.

However, this rule of thumb was for MassiveBlackII/I & P-Gadget3, where FFT was in slabs -- 16384 ranks working on nmesh=2688 is a factor of 5~6 slowdown in PM.

This number though is consistent with what we see, that the tree uses 5~6 more time than PM; for a slightly larger PM.

**Comment by sbird** [comment]
Best possible solution!

**Comment by rainwoodman** [comment]
This suggests we shall try to increase Nmesh to 3x particle to cash out the PM solver. I'll do some benchmarks.
